-- Harold Agnote
-- Professor David Brown
-- CECS 323 - Sec. 07
-- 3/15/2017

-- Lab Midterm One

-- 1.

SELECT CUSTOMERNAME, PRODUCTNAME
FROM CUSTOMERS
INNER JOIN ORDERS ON CUSTOMERS.CUSTOMERNUMBER = ORDERS.CUSTOMERNUMBER
NATURAL JOIN ORDERDETAILS
NATURAL JOIN PRODUCTS
GROUP BY CUSTOMERNAME, PRODUCTNAME
HAVING COUNT(ORDERDETAILS.PRODUCTCODE) >= 6
ORDER BY COUNT(ORDERDETAILS.PRODUCTCODE) DESC;

-- 2.

SELECT PRODUCTNAME, (MSRP/BUYPRICE) * 100 AS PERCENTPROFIT
FROM PRODUCTS
GROUP BY PRODUCTNAME, MSRP, BUYPRICE
HAVING ((MSRP/BUYPRICE) * 100) > 230
ORDER BY ((MSRP/BUYPRICE) * 100) DESC;

-- 3.

SELECT CUSTOMERNAME
FROM CUSTOMERS
LEFT JOIN ORDERS ON CUSTOMERS.CUSTOMERNUMBER = ORDERS.CUSTOMERNUMBER
WHERE ORDERS.CUSTOMERNUMBER IS NULL
ORDER BY CUSTOMERNAME;

-- 4.

SELECT one.CUSTOMERNAME, other.CUSTOMERNAME, one.STATE
FROM CUSTOMERS one
INNER JOIN CUSTOMERS other
    ON one.STATE = other.STATE
WHERE one.CUSTOMERNAME LIKE '%Inc%'
AND other.CUSTOMERNAME LIKE '%Inc%'
AND one.CUSTOMERNAME < other.CUSTOMERNAME
ORDER BY one.CUSTOMERNAME;

-- 5.


SELECT CUSTOMERNAME, COUNT(ORDERDETAILS.ORDERNUMBER)
FROM ORDERDETAILS
INNER JOIN ORDERS
    USING (ORDERNUMBER)
INNER JOIN CUSTOMERS
    ON ORDERS.CUSTOMERNUMBER = CUSTOMERS.CUSTOMERNUMBER
WHERE ORDERS.ORDERNUMBER IN
(SELECT ORDERDETAILS.ORDERNUMBER
FROM ORDERDETAILS
GROUP BY ORDERNUMBER
HAVING COUNT(ORDERNUMBER) >= 17)
GROUP BY CUSTOMERNAME
ORDER BY COUNT(ORDERDETAILS.ORDERNUMBER) DESC;

/*
SELECT CUSTOMERNAME, COUNT(ORDERDETAILS.ORDERNUMBER)
    FROM CUSTOMERS
    INNER JOIN ORDERS ON CUSTOMERS.CUSTOMERNUMBER = ORDERS.CUSTOMERNUMBER
    INNER JOIN ORDERDETAILS USING (ORDERNUMBER)
    INNER JOIN
(SELECT ORDERDETAILS.ORDERNUMBER
 FROM ORDERDETAILS
 GROUP BY ORDERNUMBER
 HAVING COUNT(ORDERNUMBER) >= 17) AS TEST
        USING (ORDERNUMBER)
GROUP BY CUSTOMERNAME
ORDER BY COUNT(ORDERDETAILS.ORDERNUMBER) DESC;
*/